### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by churnikov** [kuelumbus/rdkit_platform_wheels#1]
Hello!

I see that you intend these wheels to be used on linux, but I'd still like to know, could you give advise on how to make this work on a macOS?

**Comment by kuelumbus** [comment]
I do not use macOS and do not much about the build requirements on it. I believe this is possible. See https://cibuildwheel.readthedocs.io/en/stable

**Comment by kuelumbus** [comment]
Can you please try it the wheels at https://github.com/kuelumbus/rdkit_platform_wheels/actions/runs/790692407 work on Mac?

**Comment by churnikov** [comment]
It actually works!
![Screenshot 2021-04-29 at 12 14 50](https://user-images.githubusercontent.com/8545082/116528433-81493300-a8e4-11eb-9e61-0302e17cdde3.png)
