### ISSUE TITLE
add CAIRO_SUPPORT

### ISSUE THREAD

**Issue by skalinin** [kuelumbus/rdkit_platform_wheels#2]
Could you please add DRDK_BUILD_CAIRO_SUPPORT=ON in setup.py?

**Comment by kuelumbus** [comment]
Will push the new python packages to pypi in a couple of minutes.

**Comment by kuelumbus** [comment]
https://pypi.org/project/rdkit-pypi/2021.3.1.3/

**Comment by skalinin** [comment]
Thanks!
But now I have a new problem(
When trying to import Draw python session interrupted:

```
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit.Chem import Draw
Segmentation fault (core dumped)
```

Do you have the same problem or it's only on my computer? Use ubuntu 20.04

**Comment by kuelumbus** [comment]
Looks like there are some libraries missing. I will have a look.

**Comment by kuelumbus** [comment]
Please see if  https://pypi.org/project/rdkit-pypi/2021.3.1.4/ works.

**Comment by skalinin** [comment]
everything is work great!
thanks a lot!
