### ISSUE TITLE
add 3D descriptors support

### ISSUE THREAD

**Issue by greglandrum** [kuelumbus/rdkit_platform_wheels#4]
The 3D descriptors will be built automatically if eigen is installed on the build machines

**Comment by kuelumbus** [comment]
It works on Linux. @greglandrum can you check Mac? I've just pushed the new wheels to pypi: https://pypi.org/project/rdkit-pypi/2021.3.2.2/

```python
from rdkit import Chem
from rdkit.Chem import AllChem,Descriptors3D
m2 = Chem.AddHs(Chem.MolFromSmiles('CC'))
AllChem.EmbedMolecule(m2)
Descriptors3D.NPR1(m2)
```

**Comment by greglandrum** [comment]
@kuelumbus : confirmed; at least the intel builds work fine.
