### ISSUE TITLE
Use rdkit Chemical Features

### ISSUE THREAD

**Issue by clarissedescamps** [kuelumbus/rdkit_platform_wheels#6]
Cannot use the [Chemical Features of rdkit ](https://www.rdkit.org/docs/GettingStartedInPython.html?highlight=maccs#chemical-features-and-pharmacophores)
```
>>> from rdkit import Chem
>>> from rdkit.Chem import ChemicalFeatures
>>> from rdkit import RDConfig
>>> import os
>>> fdefName = os.path.join(RDConfig.RDDataDir,'BaseFeatures.fdef')
>>> factory = ChemicalFeatures.BuildFeatureFactory(fdefName)
```
Gives the error `OSError: File: /tmp/pip-req-build-w2hdrjg9/build/temp.linux-x86_64-3.7/rdkit_install/share/RDKit/Data/BaseFeatures.fdef could not be opened`

**Comment by kuelumbus** [comment]
That should work now in https://pypi.org/project/rdkit-pypi/2021.3.2.3/. 

Please update the packages `pip install rdkit-pypi --upgrade`
