### ISSUE TITLE
ValueError: BitVects must be same length (rdkit)

### ISSUE THREAD

**Issue by mostafiz67** [kuelumbus/rdkit_platform_wheels#7]
I am calculating the structure similarity profile between 2 moles using `rdkit`. When I am running the program in google colab (`rdkit=2020.09.2` `python=3.7`) the program is working fine.

I am getting an error when I am running on my PC (`rdkit=2021.03.2` `python=3.8.5`). The error is a bit strange. The dataframe contains `500` rows and the code is working only for the first 10 rows (0-9) and for later rows, I am getting an error 

     s = DataStructs.BulkTanimotoSimilarity(fps_2[n], fps_2[n+1:]) 
        ValueError: BitVects must be same length

The block of code is given below

    # compare all fp pairwise without duplicates
          for n in range(len(fps_2)): 
              s = DataStructs.BulkTanimotoSimilarity(fps_2[n], fps_2[n+1:]) 
              # collect the SMILES and values
              for m in range(len(s)):
                  qu.append(c_smiles2[n])
                  ta.append(c_smiles2[n+1:][m])
                  sim.append(s[m])

Can you tell me why I am getting this error on my PC while the code is working fine in Google Colab? How can I solve the issue? Is there anyway to install `rdkit=2020.09.2`?

Configuration (please complete the following information):

RDKit version: 2021.03.2
OS (not relevant): Ubuntu 20.04
Python version (not relevant):3.8.5
Are you using conda? No / `pip install rdkit-pypi` from this [link](https://pypi.org/project/rdkit-pypi/)

**Comment by kuelumbus** [comment]
Hi,
I don't think this is a problem with the wheel package. I'm transferring this to the rdkit repo. 

Your error seems to have something to do with the length of you inputs. This might help to explain the error:
https://github.com/rdkit/rdkit-orig/blob/57058c886a49cc597b0c40641a28697ee3a57aee/rdkit/DataStructs/BitVect.py#L33

**Comment by kuelumbus** [comment]
Please reopen an issue at https://github.com/rdkit/rdkit.
